### ISSUE TITLE
knoten does not ship vis

### ISSUE THREAD

**Issue by oleg-alexandrov** [USGS-Astrogeology/knoten#92]
I installed knoten with the command:

conda install -c usgs-astrogeology -c conda-forge knoten

in a fresh environment having no other packages. Then started the python from this very environment, and did 

import knoten

So far so good.

Then I did

from knoten import vis

I got the error: 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'vis'

However,  this works:

from knoten import csmapi 

Is there a reason why vis is missing from the packaged knoten? It appears to be in the repo, and if I pulled it manually it works (kind of, some apis are broken when it comes to plotly).

**Comment by oleg-alexandrov** [comment]
I figured out what the problem is. If I create a new environment on Linux as:

conda create -c usgs-astrogeology -c conda-forge python=3.6 knoten -n knoten3.6

It will install knoten 0.1.0, which is old and does not have vis.

Yet python 3.6 is what ISIS uses. 

If I do:

conda create -c usgs-astrogeology -c conda-forge python=3.7 knoten -n knoten3.7

then I get knoten 0.2.1, which is the latest.  But then I get into another problem which I found in a different place as well:

import knoten
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/oalexan1/miniconda3/envs/knoten3.7/lib/python3.7/site-packages/knoten/__init__.py", line 7, in <module>
    from . import csm
  File "/home/oalexan1/miniconda3/envs/knoten3.7/lib/python3.7/site-packages/knoten/csm.py", line 7, in <module>
    from gdal import ogr
ModuleNotFoundError: No module named 'gdal'

Anyhow, both this package and the notebooks need a bit of updating.
